name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: sudo xcode-select -switch /Applications/Xcode_14.1.app
      - run: swift test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: norio-nomura/action-swiftlint@3.2.1
